install-deps:
    #!/bin/bash
    set -e

    # Source distro info
    if [ -f /etc/os-release ]; then
        . /etc/os-release
    else
        echo "Cannot detect OS."
        exit 1
    fi

    echo "Detected distro: ID=$ID, ID_LIKE=$ID_LIKE"

    # Normalize variables (in case ID_LIKE is a space-separated list)
    DISTRO="$ID $ID_LIKE"

    if echo "$DISTRO" | grep -qE 'debian|ubuntu'; then
        echo "Installing debian/ubuntu dependencies with apt..."
        sudo apt update && sudo apt install -y \
          build-essential \
          cargo \
          cmake \
           libxkbcommon-dev libudev1 libinput10 libcap2 libmtdev1 libevdev2 libwacom9 libgudev-1.0-0 \
           libglib2.0-dev libffi8 libpcre2-dev libxkbcommon-x11-dev libxcb-dev libxcb-xkb-dev libxau-dev \ 
           libstdc++-dev libx11-dev libxfixes-dev libegl-dev libgbm-dev libfontconfig1-dev libgl-dev \
           libdrm-dev libexpat1-dev libfreetype6-dev libxml2-dev zlib1g-dev libbz2-dev libpng-dev \ 
           libharfbuzz-dev libbrotli-dev liblzma-dev libraphite2-dev

    elif echo "$DISTRO" | grep -qE 'fedora'; then
        echo "Installing fedora dependencies with dnf..."
          # Install development tools group
          sudo dnf group install -y development-tools \
          # Install individual packages grouped by functionality
          sudo dnf install -y \
            cargo cmake \
            libxkbcommon-devel systemd-devel libinput-devel libcap-devel mtdev-devel libevdev-devel glib2-devel \
            libffi-devel pcre2-devel libxkbcommon-x11-devel libxcb-devel libXau-devel libstdc++-devel libx11-devel libxfixes-devel \
            mesa-libEGL-devel mesa-libgbm-devel fontconfig-devel libdrm-devel expat-devel freetype-devel libxml2-devel zlib-devel \
            bzip2-devel libpng-devel harfbuzz-devel brotli-devel xz-devel graphite2-devel

    elif echo "$DISTRO" | grep -q 'arch'; then
        echo "Installing arch dependencies with pacman..."
        sudo pacman -Sy --noconfirm \
          cargo \ 
          cmake \
          sudo pacman -Syu --needed \
          libxkbcommon systemd libinput libcap mtdev libevdev libwacom glib2 libffi pcre2 libxkbcommon-x11 \
          libxcb libxau libx11 libxfixes mesa fontconfig libdrm expat freetype2 libxml2 zlib bzip2 \ 
          libpng harfbuzz brotli xz graphite
    else
        echo "Unsupported distro: $ID"
        exit 1
    fi


# install all repos into prefix folder
cargo-install-repos:
    #!/usr/bin/env bash
    PREFIX_DIR="./prefix"
    mkdir -p "$PREFIX_DIR"

    # Create/update root .gitignore to exclude the prefix directory
    if [[ ! -f .gitignore ]]; then
      echo "# Automatically generated by install script" > .gitignore
    fi
    if ! grep -q "^/prefix/$" .gitignore; then
      echo "/prefix/" >> .gitignore
      echo "Added /prefix/ to .gitignore"
    fi

    # Recursively find all Rust crates (must have both Cargo.toml AND src/)
    shopt -s globstar
    REPO_DIRS=()
    for dir in **/; do
        if [[ -f "$dir/Cargo.toml" && -d "$dir/src" ]]; then
            REPO_DIRS+=("$dir")
        fi
    done

    # Install all collected crates
    for dir in "${REPO_DIRS[@]}"; do
        echo "Installing from $dir to $PREFIX_DIR"
        cargo install --path "$dir" --root "$PREFIX_DIR" --bins --locked --force
    done

    echo "Successfully processed ${#REPO_DIRS[@]} crates"

        if [[ -d "$entry" ]]; then
            echo "$(basename "$entry")"
        fi
    done

# Install an XR environment
atmosphere-manual-installation:
  echo "Insert location of an env.kdl file:"
  read -r XR_ENV_LOCATION
  ./prefix/bin/atmosphere install XR_ENV_LOCATION

run-stardust-xr:
  dbus-run-session ./prefix/bin/stardust-xr-server -e startup.sh

# Create a new client from template
new-client:
    #!/usr/bin/env bash
    echo "Enter new client name:"
    read -r CLIENT_NAME
    
    # Copy template
    if [ ! -d "client-template" ]; then
        echo "Error: client-template directory not found!"
        exit 1
    fi
    
    cp -r client-template "$CLIENT_NAME"
    
    # Rename crate in Cargo.toml
    sed -i "s/^name = \".*\"/name = \"$CLIENT_NAME\"/" "$CLIENT_NAME/Cargo.toml"
    
    # Install the client
    echo "Installing new client..."
    cargo install --path "$CLIENT_NAME" --root ./prefix --bins --locked --force
    echo "Client '$CLIENT_NAME' created and installed!"

# Update an existing client
update-client:
    #!/usr/bin/env bash
    echo "Enter client name to update:"
    read -r CLIENT_NAME
    
    shopt -s globstar
    FOUND_DIR=""
    for dir in **/; do
        if [[ -f "$dir/Cargo.toml" && -d "$dir/src" ]]; then
            # Check for matching binary files
            if [[ -f "$dir/src/bin/$CLIENT_NAME.rs" || 
                  ( -f "$dir/src/main.rs" && $(grep -oP '^name = "\K[^"]+' "$dir/Cargo.toml") == "$CLIENT_NAME" ) ]]; then
                FOUND_DIR="$dir"
                break
            fi
        fi
    done

    if [[ -z "$FOUND_DIR" ]]; then
        echo "Error: Client '$CLIENT_NAME' not found!"
        echo "Searched for:"
        echo "1. src/bin/$CLIENT_NAME.rs"
        echo "2. crates named '$CLIENT_NAME' with src/main.rs"
        exit 1
    fi
    
    echo "Found client at: $FOUND_DIR"
    echo "Updating client '$CLIENT_NAME'..."
    cargo install --path "$FOUND_DIR" --root ./prefix --bins --locked --force
    echo "Successfully updated client '$CLIENT_NAME'"



